### ISSUE TITLE
Gotest Versions Not Found

### ISSUE THREAD

**Issue by time-less-ness** [Dominic-Wassef/ghostly#4]
Any ideas what causes this? I am just trying a regular `make build` from a straight checkout of `main`.

```
go: finding gotest.tools/v3 v3.0.3
go: finding gotest.tools/v3 v3.0.2
go: gotest.tools/v3@v3.0.2: unknown revision gotest.tools/v3.0.2
go: gotest.tools/v3@v3.0.3: unknown revision gotest.tools/v3.0.3
go: error loading module requirements
make: *** [build] Error 1
```

**Comment by Dominic-Wassef** [comment]
Now what make commands are you using and what is the operating system? I make no guarantees for Windows as I only have access to Mac and Linux, it should work once you git clone the repo, cd into it and "make build" only at root level of project. The binary would be in the dist folder

**Comment by time-less-ness** [comment]
I'm going to guess something is just messed up about my situation. I deleted go.sum...

```
[~/Dev/ghostly] ⎇ main :) ls -al go.sum
ls: go.sum: No such file or directory

[~/Dev/ghostly] ⎇ main :) go mod tidy
go: finding gotest.tools/v3 v3.0.3
go: finding gotest.tools/v3 v3.0.2
go: gotest.tools/v3@v3.0.2: unknown revision gotest.tools/v3.0.2
go: gotest.tools/v3@v3.0.3: unknown revision gotest.tools/v3.0.3
go: error loading module requirements

[~/Dev/ghostly] ⎇ main :) go mod graph
go: finding gotest.tools/v3 v3.0.3
go: finding gotest.tools/v3 v3.0.2
go: gotest.tools/v3@v3.0.3: unknown revision gotest.tools/v3.0.3
go: gotest.tools/v3@v3.0.2: unknown revision gotest.tools/v3.0.2
go: error loading module requirements

[~/Dev/ghostly] ⎇ main :) go mod why
go: finding gotest.tools/v3 v3.0.3
go: finding gotest.tools/v3 v3.0.2
go: gotest.tools/v3@v3.0.3: unknown revision gotest.tools/v3.0.3
go: gotest.tools/v3@v3.0.2: unknown revision gotest.tools/v3.0.2
go: error loading module requirements
```

Something is just super-insistent that I need these modules, but nothing I can find in Ghostly. Maybe there's some global config I have broken. I'll poke around and if I find anything I'll post back here.

**Comment by Dominic-Wassef** [comment]
Double check your go path as that can cause problems, especially dealing with deps..
Docs: https://go.dev/doc/gopath_code#GOPATH

Below is what it should looks like once the binary is built.

`Error: command required
Available commands:

	help                           - show the help commands
	version                        - print application version
	migrate                        - runs all up migrations
	migrate down                   - reverses most recent migration
	migrate reset                  - runs all down / up migrations
	make migration <name> <format> - two new up and down migrations
	make auth                      - new auth tables, models, middleware
	make handler <name>            - stub handler in the handlers folder
	make model <name>              - new model in the data directory
	make session                   - database table as a session store
	make mail <name>               - two starter mail templates


Error: command required
Finished!`

**Comment by Dominic-Wassef** [comment]
Reach back out if you have any other issues, I will be closing this for now as it's an issue outside of ghostly
